name: receipts_list_dummy_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^7.3.0
  bloc: ^7.0.0
  equatable: ^2.0.0
  meta: ^1.3.0
  camera: ^0.9.4+1
  formz: ^0.4.0
  image_picker: ^0.8.4+2
  image: 3.0.8
  gpx: ^2.1.0

  # Google stuff
  firebase_core: ^1.7.0
  firebase_storage: ^10.0.5
  google_maps_flutter: ^2.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/map_graph_dummy.gpx